version: 3.0.2

branches:
  only:
  - master

image: Visual Studio 2017
configuration: Release
platform: Any CPU

dotnet_csproj:
  patch: false
  file: '**\*.csproj'
  version: '{version}'

nuget:
  disable_publish_on_pr: true

clone_folder: C:\projects\ceras

before_build:
- cmd: nuget restore

build_script:
  - msbuild "C:\projects\ceras\src\Ceras\Ceras.csproj" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild "C:\projects\ceras\tests\Ceras.Test\Ceras.Test.csproj" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

before_package:
- cmd: >-
    7z a ceras_net45.zip "src\Ceras\bin\Release\net45\Ceras.dll" "src\Ceras\bin\Release\net45\Ceras.pdb"

    7z a ceras_netstandard2.0.zip "src\Ceras\bin\Release\netstandard2.0\Ceras.dll" "src\Ceras\bin\Release\netstandard2.0\Ceras.pdb"

artifacts:
- path: ceras_net45.zip
  name: Release Folder Zip (.NET Framework 4.5)
- path: '**\Ceras*.nupkg'
  name: NuGet Package
- path: ceras_netstandard2.0.zip
  name: Release Folder Zip (.net standard 2.0)
